Fixed use of keyidentifier
theintern/recorder pull request #8
Opened 2017-02-02 18:20 UTC by mrawdon

This fixes #6
keyIdentifier was replaced in favor of key https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyIdentifier

2017-02-02 18:25 UTC, dylans requested changes
minor whitespace nit, otherwise looks fine to me.

2017-02-02 18:25 UTC, dylans commented on lib/EventProxy.js
> +
extra whitespace?

2017-02-03 14:13 UTC, jason0x43 commented
This will break Safari, which still uses `keyIdentifier`. We'll need to try both `keyIdentifier` and `key` when getting the value from the event.

2017-02-03 15:12 UTC, mrawdon commented
I added a fallback for keyIdentifier if key isn't defined

2017-02-03 15:35 UTC, dylans reviewed
Are all other instances of event.key working through the EventProxy? (I've not had time to verify...) If so, this looks fine, otherwise there are a few other places that need similar treatment.

2017-02-03 15:43 UTC, mrawdon commented
As far as I could tell this was the only place where the key was pulled from the event in EventProxy.  It works for me in Chrome I'm not able to test Safari though

2017-04-03 18:45 UTC, The-Alchemist approved these changes

2017-04-07 21:54 UTC, dylans approved these changes

2017-06-16 13:06 UTC, wizzard0 commented
and... was it eventually merged?

2017-06-16 13:19 UTC, jason0x43 commented
Merged in a9f7c14f68a18752ca1b07dea530f0835dff061b. Thanks!

2017-06-16 13:19 UTC, closed without merging